# Generated by Django 4.2.3 on 2023-07-28 04:04

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_sleep_options_remove_sleep_napping_sleep_nap"),
    ]

    operations = [
        migrations.CreateModel(
            name="BathTime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime,
                        verbose_name="Start time",
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="End time"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        editable=False, null=True, verbose_name="Duration"
                    ),
                ),
                (
                    "milestone",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Milestone"
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bath_time",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "tags",
                    core.models.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="core.Tagged",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bath Time",
                "verbose_name_plural": "Bath Time",
                "ordering": ["-start"],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
    ]
